backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img


collections:
  - name: "project" # Used in routes, e.g., /admin/collections/blog
    label: "Project" # Used in the UI
    folder: "src/pages/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    path: "projects/{{slug}}"
    editor:
      preview: true # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "project"}
      # - {label: "Title", name: "title", widget: "string"}
      - label: "Title of the project ex: 'Project 1'"
        name: "title" 
        widget: "string" 
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", media_folder: "{{media_folder}}/project", public_folder: "{{public_folder}}/project"}
      - label: "Slug (please follow format of project and project number ex: 'project1'"
        name: "slug"
        widget: "string"
        pattern: ['project\d{1,}', "Must be lowercase ep followed by a number"]
      - label: "Tools Used:"
        name: "tools"
        widget: "markdown"
      - label: "Project URL"
        name: "url"
        widget: "string"
      - label: "Description of project."
        name: "body"
        widget: "markdown"
      
  #Events
  - name: "event" # Used in routes, e.g., /admin/collections/blog
    label: "Event" # Used in the UI
    folder: "src/pages/events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    path: "events/{{slug}}"
    editor:
      preview: true  # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "event"}
      - label: "Title"
        name: "title"
        widget: "string"
      - {label: "Event Date", name: "date", widget: "datetime"}
      - label: "Body"
        name: "body"
        widget: "markdown"
      - {label: "URL", name: "url", widget: "string"}